apiVersion: v1
kind: ConfigMap
metadata:
  name: shortener-config
  namespace: shortener
data:
  NODE_ENV: production
  BASE_URL: http://linkuj.rurek.org/
  FRONTEND_URL: http://web:80
  URL_SERVICE_URL: http://url-service:3001
  REDIRECT_SERVICE_URL: http://redirect-service:3002
  PUBLIC_TURNSTILE_SITE_KEY: TWOJ_SITE_KEY
